version: '2'
services:
  website:
    build: ./website
    restart: always
    ports:
      - 8080:80
  application:
    build: ./application
    restart: always
    network_mode: host
    env_file: .env
    environment:
      - MESG_ENDPOINT=host.docker.internal:50052